/*
CREATE TABLE MOV_PEDIDO_WEB_DO(
  CODFIL NUMBER(3, 0) NOT NULL,
  NUMPEDVEN NUMBER(8, 0) NOT NULL,
  TENTAIVASPGTO NUMBER(2, 0) NOT NULL,
  PAGO CHAR(1 BYTE) NOT NULL,
  RETORNO VARCHAR2(4000),
  OBSERVACAO VARCHAR2(4000), 
  CONSTRAINT MOV_PEDIDO_WEB_DO_PK PRIMARY KEY(CODFIL, NUMPEDVEN)
);



CREATE INDEX MOV_PEDIDO_WEB_DO_PED_I ON MOV_PEDIDO_WEB_DO (NUMPEDVEN) NOPARALLEL;

--04/09/2008 - Mário - sinonimo público
CREATE PUBLIC SYNONYM MOV_PEDIDO_WEB_DO FOR MOV_PEDIDO_WEB_DO@LNKLVIRT

--21/11/2011 - Mandelli - bradesco
ALTER TABLE mov_pedido_web_do
ADD data_pagamento DATE;
*/

alter table mov_pedido_web_do add constraint pk_mov_pedido_web_do primary key (NUMPEDVEN);