CREATE TABLE "WEBSITE"."ULTIMAS_CATEGORIAS_VISITADAS"
  (
    "CODIGO"           NUMBER(10,0) NOT NULL ENABLE,
    "CODCLILV"         NUMBER(10,0) NOT NULL ENABLE,
    "TIPO"             VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "CODIGO_CATEGORIA" NUMBER(10,0) NOT NULL ENABLE,
    "DT_VISUALISADO" DATE,
    CONSTRAINT "ULTIMAS_CATEGORIAS_VISITA_PK" PRIMARY KEY ("CODIGO") ENABLE,
    CONSTRAINT "ULTIMAS_CATEGORIAS_VIS_CAT_CLI" UNIQUE ("CODCLILV", "TIPO", "CODIGO_CATEGORIA") ENABLE,
    CONSTRAINT "ULTIMAS_CATEGORIAS_VIS_USUARIO" FOREIGN KEY ("CODCLILV") REFERENCES "WEBSITE"."WEB_USUARIOS" ("CODCLILV") ENABLE
  );