CREATE TABLE "WEBSITE"."ULTIMOS_PRODUTOS_VISITADOS"
  (
    "CODCLILV" NUMBER(10,0) NOT NULL ENABLE,
    "CODPROD"  NUMBER(10,0) NOT NULL ENABLE,
    "DATA_VISITADO" DATE,
    CONSTRAINT "ULTIMOS_VISITADOS_CLIENTE_PK" PRIMARY KEY ("CODCLILV", "CODPROD") ENABLE,
    CONSTRAINT "ULTIMOS_PRODUTOS_VISITADO_FK1" FOREIGN KEY ("CODCLILV") REFERENCES "WEBSITE"."WEB_USUARIOS" ("CODCLILV") ENABLE,
    CONSTRAINT "ULTIMOS_PRODUTOS_VISITADO_FK2" FOREIGN KEY ("CODPROD") REFERENCES "WEBSITE"."WEB_PROD" ("CODPROD") ENABLE
  )