CREATE TABLE "WEBSITE"."WEB_INTEGR_CAMPO"
  (
    "COD"     NUMBER NOT NULL ENABLE,
    "NOME"    VARCHAR2(30 BYTE) NOT NULL ENABLE,
    "DESCR"   VARCHAR2(200 BYTE),
    "ORDEM"   CHAR(1 BYTE),
    "FLCDATA" CHAR(1 BYTE),
    "CHAVE"   VARCHAR2(20 BYTE),
    PRIMARY KEY ("COD") );