CREATE TABLE WEB_ITPROD_BRINDEPLANO
	(
		COD_BRINDE  NUMBER(10,0) NOT NULL ENABLE,
		CODPLANO    VARCHAR2(3 BYTE) NOT NULL ENABLE,
		FLDESCLISTA CHAR(1 BYTE) NOT NULL ENABLE,
		QTDPRC      NUMBER(3,0),
		DTALTER DATE,
		USALTER       VARCHAR2(20 BYTE),
		TAXA          NUMBER(15,2),
		PRECO         NUMBER(15,2),
		PRECOANTERIOR NUMBER(15,2),
		PRIMARY KEY ("COD_BRINDE", "CODPLANO"),
		FOREIGN KEY ("COD_BRINDE") REFERENCES "WEBSITE"."WEB_ITPROD_BRINDE" ("COD_BRINDE") ENABLE,
		FOREIGN KEY ("CODPLANO") REFERENCES "WEBSITE"."WEB_PLANO" ("CODPLANO") ENABLE
)
