
  CREATE TABLE "WEBSITE"."WEB_SELO_IMAGEM" 
   (	"CODIGO" NUMBER(10,0) NOT NULL ENABLE, 
	"SELO" NUMBER(10,0), 
	"PATH" VARCHAR2(300 BYTE), 
	 CONSTRAINT "WEB_SELO_IMAGEM_PK" PRIMARY KEY ("CODIGO")  ENABLE, 
	 CONSTRAINT "WEB_SELO_IMAGEM_SELO" FOREIGN KEY ("SELO")
	  REFERENCES "WEBSITE"."WEB_SELO" ("CODIGO") ENABLE
   );
 
