-- JoaoP 03/04/2013


  CREATE TABLE "WEBSITE"."WEB_INTEGR_PORTAL_FILTRO_LOG" 
   (	"CODIGO" NUMBER(10,0), 
	"COD_INTEGR_PORTAL" NUMBER(10,0), 
	"FILTRO" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"DATA_CADASTRO" DATE NOT NULL ENABLE, 
	"USUARIO_CADASTRO" VARCHAR2(200 BYTE), 
	"OPERACAO" VARCHAR2(1 BYTE), 
	 PRIMARY KEY ("CODIGO"), 
	 CONSTRAINT "FK_WEB_INTEGR_PORTAL_LOG" FOREIGN KEY ("COD_INTEGR_PORTAL")
	  REFERENCES "WEBSITE"."WEB_INTEGR_PORTAL" ("COD")
  );
  
 
