-- Quantidade de registros: +/- 100

CREATE TABLE WEB_PROD_RSS (
  RSS_ID NUMBER(10) NOT NULL,
  RSS_DT_PUBLICACAO DATE NOT NULL,
  RSS_TXT_TIPO_PUBLICACAO VARCHAR2(1) NOT NULL,
  PRD_COD_PROD NUMBER(10), 
    CONSTRAINT WEB_PROD_RSS_PK PRIMARY KEY (RSS_ID)
);

ALTER TABLE WEB_PROD_RSS ADD CONSTRAINT WEB_PROD_RSS_PROD_FK FOREIGN KEY (PRD_COD_PROD) REFERENCES WEB_PROD (CODPROD);

CREATE INDEX WEB_PROD_RSS_PROD_FKI ON WEB_PROD_RSS (PRD_COD_PROD);

CREATE SEQUENCE SEQ_WEB_PROD_RSS;