  CREATE TABLE "WEBSITE"."WEB_EXCLUSAO_RESPONSYS" 
   (	"CODIGO" NUMBER NOT NULL ENABLE, 
	"DT_CADASTRO" DATE, 
	"TIPO" VARCHAR2(30 BYTE), 
	"FL_ENVIADO_RESPONSYS" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"CODIGO_EXCLUSAO" VARCHAR2(20 BYTE), 
	 CONSTRAINT "WEB_EXLCUSAO_RESPONSYS_PK" PRIMARY KEY ("CODIGO")  ENABLE
   );
 
