--
-- Armazena os planos de pagamento para o site
-- 20 registros no total
--
  CREATE TABLE "WEBSITE"."WEB_PLANO" 
   (	"CODPLANO" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"TAXA" NUMBER(15,2) NOT NULL ENABLE, 
	"QTDPRC" NUMBER(2,0) NOT NULL ENABLE, 
	"TPPGTO" NUMBER(2,0) NOT NULL ENABLE, 
	"DTINICIO" DATE NOT NULL ENABLE, 
	"DTFIM" DATE NOT NULL ENABLE, 
	"DTALTER" DATE, 
	"USERALTER" VARCHAR2(20 BYTE), 
	"VLMINPARC" NUMBER(15,2) NOT NULL ENABLE, 
	"FLGITEM" CHAR(1 BYTE) NOT NULL ENABLE, 
	"FLENTRADA" CHAR(1 BYTE) DEFAULT 'S' NOT NULL ENABLE, 
	"CODPLANOGEMCO" VARCHAR2(3 BYTE), 
	"MARGEMMINIMA" NUMBER(15,2), 
	 CONSTRAINT "WEB_PLANO_PK" PRIMARY KEY ("CODPLANO") ENABLE, 
	 CONSTRAINT "WEB_PLANO_FK" FOREIGN KEY ("TPPGTO")
	  REFERENCES "WEBSITE"."WEB_TPPGTO" ("TPPGTO") ENABLE
   ) ;

-- 01/06/2006 - Lucas - Alteracao de campos para o sistema do televendas
ALTER TABLE WEB_PLANO ADD ("FLSITE" CHAR(1) DEFAULT 'S' NOT NULL);
ALTER TABLE WEB_PLANO ADD ("FLTELE" CHAR(1) DEFAULT 'S' NOT NULL);
ALTER TABLE WEB_PLANO ADD ("FLMELHOR" CHAR(1) DEFAULT 'S' NOT NULL);
ALTER TABLE WEB_PLANO ADD ("MARGEMMINIMA" NUMBER(15,2));

-- 27/11/2006 - Lucas - Descontos por plano no site
ALTER TABLE WEB_PLANO ADD ("VLRDESCONTO" NUMBER(15, 2));
ALTER TABLE WEB_PLANO ADD ("PERDESCONTO" NUMBER(15, 4));

-- 15/12/2006 - Lucas - Dias de pagamento entre as parcelas
ALTER TABLE WEB_PLANO ADD ("DIASPGTO" NUMBER(3));

-- 06/08/2007 - Lucas - Nova utilizacao planos
ALTER TABLE WEB_PLANO RENAME COLUMN "FLSITE" TO "FLATIVO" ;
ALTER TABLE WEB_PLANO DROP COLUMN "FLGITEM";
ALTER TABLE WEB_PLANO DROP COLUMN "FLTELE";
ALTER TABLE WEB_PLANO DROP COLUMN "MARGEMMINIMA";

-- 08/10/2007 - Lucas - Entrada e pagamento ficam no tipo de pgto
ALTER TABLE WEB_PLANO DROP COLUMN "FLENTRADA";
ALTER TABLE WEB_PLANO DROP COLUMN "DIASPGTO";

-- 23/07/2008 - Thiago - Flag de rebate financeiro
ALTER TABLE WEB_PLANO ADD ("FLREBATEFINANCEIRO" CHAR(1)); 

-- 07/10/2008 - thiago
ALTER TABLE WEB_PLANO DROP COLUMN "FLREBATEFINANCEIRO";
create unique index idx_web_plano_tppgto on web_plano (tppgto);

-- 09/05/2012 - Aquiles - adicionar juros apartir de uma parcela especifica
ALTER TABLE WEB_PLANO ADD ("JUROS_PARCELA" NUMBER(2) DEFAULT 1 NOT NULL);
