-- 20 registros por dia

  CREATE TABLE "WEBSITE"."WEB_CAMP_PRECO_PROD_PLANOS" 
   (	CPP_ID NUMBER(10) NOT NULL, 
	CPD_ID NUMBER(10) NOT NULL, 
	PLA_CODPLANO VARCHAR2(3) NOT NULL, 
	CPP_JUROS NUMBER(5,2), 
        CPP_PARCELAS NUMBER(3) NOT NULL, 
        CPP_VALOR_FINAL NUMBER(15,2),
	CONSTRAINT "WEB_CAMP_PRECO_PROD_PLANOS_PK" PRIMARY KEY ("CPP_ID"),
        CONSTRAINT "WEB_CPP_FK_WEB_CPD" FOREIGN KEY (CPD_ID) REFERENCES "WEBSITE"."WEB_CAMP_PRECO_PRODUTOS" (CPD_ID),
        CONSTRAINT "WEB_CPP_FK_WEB_PLANO" FOREIGN KEY (PLA_CODPLANO) REFERENCES "WEBSITE"."WEB_PLANO" (CODPLANO)
);

CREATE SEQUENCE SEQ_ID_WEB_CAMP_PREC_PROD_PLAN INCREMENT BY 1 START WITH 1 ; 

--
-- Alteração para integações e importações automáticas.
-- DESATIVAR TODAS AS TRIGGERS ANTES DE INCLUIR ESTA COLUNA
alter table web_camp_preco_prod_planos add flg_processa_online varchar2(1) default 'S' not null;

-- 09/05/2012 - Aquiles - adicionar juros apartir de uma parcela especifica
ALTER TABLE WEB_CAMP_PRECO_PROD_PLANOS ADD ("CPP_JUROS_PARCELA" NUMBER(2) DEFAULT 1 NOT NULL);