/*
CREATE TABLE "WEBSITE"."WEB_LANDING_PAGE1"
  (
    "CODIGO"       NUMBER(10,0) NOT NULL ENABLE,
    "PALAVRACHAVE" VARCHAR2(200 BYTE) NOT NULL ENABLE,
    "FLATIVO"      CHAR(1 BYTE),
    "BANNER"       NUMBER(6,0),
    "DESCRICAO"    VARCHAR2(200 BYTE) NOT NULL ENABLE,
    CONSTRAINT "WEB_LANDING_PAGE_PK" PRIMARY KEY ("CODIGO") ENABLE,
    CONSTRAINT "UK_WEB_LANDING_PAGE_DESCRICAO" UNIQUE ("DESCRICAO")  ENABLE,
    CONSTRAINT "UK_WEB_LANDING_PAGE_PCHAVE" UNIQUE ("PALAVRACHAVE")  ENABLE
  )
  */

-- Inclusão de caminha para arquivo hotsite na landing page
ALTER TABLE web_landing_page 
ADD arquivo_principal varchar2(1000);
