CREATE TABLE "WEBSITE"."WEB_BRINDE_AGREGADOS_IMAGEM"
  (
    "CODIGO"     NUMBER(10,0) NOT NULL ENABLE,
    "COD_BRINDE" NUMBER(10,0),
    "ORDEM"      NUMBER(3,0),
    "DT_ALTERACAO" DATE,
    "PATH"         VARCHAR2(300 BYTE),
    "FLZOOM"       VARCHAR2(1 CHAR) DEFAULT 'N',
    "COD_AGREGADA" NUMBER(10,0),
    CONSTRAINT "WEB_BRINDE_AGREGADOS_IMAG_PK" PRIMARY KEY ("CODIGO") ENABLE,
    CONSTRAINT "WEB_BRINDE_AGRE_IMAG_FK_BRINDE" FOREIGN KEY ("COD_BRINDE") REFERENCES "WEBSITE"."WEB_ITPROD_BRINDE" ("COD_BRINDE") ENABLE,
    CONSTRAINT "WEB_BRINDE_AGRE_IMA_FK_VD_AGR" FOREIGN KEY ("COD_AGREGADA") REFERENCES "WEBSITE"."WEB_PROD_VENDA_AGREGADA" ("PVA_ID") ENABLE
  )