-- 3 registros por dia
  CREATE TABLE "WEBSITE"."WEB_CAMPANHAS_PRECO" 
   (	CPR_ID NUMBER(10) NOT NULL, 
	CPR_DESCRICAO VARCHAR2(40) NOT NULL, 
	CPR_INICIO DATE NOT NULL, 
	CPR_FIM DATE NOT NULL, 
	CPR_FL_ATIVO CHAR(1) NOT NULL,
	CONSTRAINT "WEB_CAMPANHAS_PRECO_PK" PRIMARY KEY ("CPR_ID")
);

CREATE SEQUENCE SEQ_ID_WEB_CAMPANHAS_PRECO INCREMENT BY 1 START WITH 1 ; 

--Cesar Augusto, Timer 15/7/2015
alter table web_campanhas_preco
add(
	CODIGO_TIMER NUMBER(10,0),
	CONSTRAINT FK_CODIGO_TIMER FOREIGN KEY(CODIGO_TIMER) REFERENCES WEB_TIMER(CODIGO)
);