CREATE TABLE "WEBSITE"."WEB_GRUPO_SECUNDARIO"
(
	"CODPROD" NUMBER(6,0) NOT NULL ENABLE,
	"CODGRUPO" NUMBER(6,0) NOT NULL ENABLE,
	"CODGRUPOSECUNDARIO" NUMBER(6,0) NOT NULL ENABLE,
	 CONSTRAINT "WEB_GRUPO_SECUNDARIO_PK" PRIMARY KEY ("CODGRUPOSECUNDARIO"),
	 CONSTRAINT "WEB_GRUPO_SECUNDARIO_GRUPO" FOREIGN KEY ("CODGRUPO")
	  REFERENCES "WEBSITE"."WEB_GRUPO" ("CODGRUPO") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "WEB_GRUPO_SECUNDARIO_PRODUTO" FOREIGN KEY ("CODPROD")
	  REFERENCES "WEBSITE"."WEB_PROD" ("CODPROD") ON DELETE CASCADE ENABLE
);

