
CREATE TABLE "WEBSITE"."WEB_TEXTO_PAGINA_AGENDA" 
   (	"CODIGO" NUMBER(10,0) NOT NULL ENABLE, 
	"CODABA" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"IDIOMA" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"FL_ATIVO" CHAR(1 BYTE), 
	"DTINI" DATE, 
	"DTFIM" DATE, 
	"HRINI" DATE, 
	"HRFIM" DATE, 
	"FL_DOM" CHAR(1 BYTE), 
	"FL_SEG" CHAR(1 BYTE), 
	"FL_TER" CHAR(1 BYTE), 
	"FL_QUA" CHAR(1 BYTE), 
	"FL_QUI" CHAR(1 BYTE), 
	"FL_SEX" CHAR(1 BYTE), 
	"FL_SAB" CHAR(1 BYTE), 
	"HTML" CLOB, 
	 PRIMARY KEY ("CODIGO")
);
