-- 02/2012 Mandelli
CREATE TABLE "WEBSITE"."WEB_INTEGR_PORTAL_BRINDE"
(
  "CODIGO"            NUMBER(*,0) NOT NULL ENABLE,
  "COD_INTEGR_PORTAL" NUMBER(*,0) NOT NULL ENABLE,
  "CODBRINDE"           NUMBER(6,0) NOT NULL ENABLE,
  "DATA_INCLUSAO" DATE NOT NULL ENABLE,
  "FL_ATIVO"        CHAR(1 BYTE) DEFAULT 'S' NOT NULL ENABLE,
  "FL_PRECO_CARTAO" CHAR(1 BYTE) DEFAULT 'N',
  CONSTRAINT "PK_WEB_INTEGR_PORTAL_BRINDE" PRIMARY KEY ("CODIGO"),
  CONSTRAINT "UK_WEB_INTEGR_PORTAL_BRINDE" UNIQUE ("COD_INTEGR_PORTAL", "CODBRINDE"),
  CONSTRAINT "CK_INTEGR_PORTAL_BRINDE" CHECK (fl_preco_cartao IN ('N','S')) ENABLE,
  CONSTRAINT "FK_INTEGR_PORTAL_BRINDE_POR" FOREIGN KEY ("COD_INTEGR_PORTAL") REFERENCES "WEBSITE"."WEB_INTEGR_PORTAL" ("COD") ENABLE
)