--
-- Armazena os usuarios cadastrados no site
-- 1000 registros / mes
--
  CREATE TABLE "WEBSITE"."WEB_USUARIOS_COMPL" 
   (	"USUARIO" NUMBER(15,0), 
	"NRODEPENDENTES" NUMBER(2,0), 
	"CPFCONJUGE" NUMBER(15,0), 
	"NATUREZA" VARCHAR2(1 BYTE), 
	"CARGOCONJUGE" NUMBER(6,0), 
	"ESCOLARIDADE" VARCHAR2(1 BYTE), 
	"CHEQUEESPECIAL" VARCHAR2(1 BYTE), 
	"DTABERTURACONTA" DATE, 
	 PRIMARY KEY ("USUARIO"))
