-- Armazena os limites para o item
-- 50.000 registros total

  CREATE TABLE "WEBSITE"."WEB_ITPROD_LIMITES" 
   (	"CODFIL" NUMBER(3,0) NOT NULL ENABLE, 
	"CODITPROD" NUMBER(6,0) NOT NULL ENABLE, 
	"PRECO" NUMBER(10,2), 
	"MARGEM" NUMBER(6,4), 
	"DESCONTO" NUMBER(6,4), 
	 CONSTRAINT "WEB_ITPROD_LIMITES_PK" PRIMARY KEY ("CODFIL", "CODITPROD")
  );
 