CREATE TABLE WEB_PROD_TP_CARACTERISTICA
(
	PTPC_ID decimal(10,0) PRIMARY KEY NOT NULL,
   	DESCRICAO varchar2(255)
);
INSERT INTO WEB_PROD_TP_CARACTERISTICA (PTPC_ID,DESCRICAO) VALUES (0,'Prós');
INSERT INTO WEB_PROD_TP_CARACTERISTICA (PTPC_ID,DESCRICAO) VALUES (1,'Contras');