CREATE TABLE WEB_DESCONTOS_PLANO 
  (DPL_ID NUMBER(10,0) NOT NULL ENABLE, 
   DES_CODDESCONTO NUMBER(15,0) NOT NULL ENABLE, 
   PLA_CODPLANO VARCHAR2(3 BYTE) NOT NULL ENABLE, 
   DPL_PRECO NUMBER(10,2) NOT NULL ENABLE, 

  CONSTRAINT WEB_DESCONTOS_PLANO_PK PRIMARY KEY (DPL_ID),
  CONSTRAINT FK_DESCONTOS_PLANO_DESC FOREIGN KEY (DES_CODDESCONTO)
   REFERENCES WEB_DESCONTOS (CODDESCONTO), 
  CONSTRAINT FK_DESCONTOS_PLANO_PL FOREIGN KEY (PLA_CODPLANO)
  REFERENCES WEB_PLANO (CODPLANO));
 
CREATE INDEX WEB_DESCONTOS_PLANO_DES_FKI ON WEB_DESCONTOS_PLANO (DES_CODDESCONTO);
CREATE UNIQUE INDEX WEB_DESCONTOS_PLANO_PK ON WEB_DESCONTOS_PLANO (DPL_ID);
CREATE INDEX WEB_DESCONTOS_PLANO_PL_FKI ON WEB_DESCONTOS_PLANO (DPL_PRECO);

CREATE SEQUENCE SEQ_WEB_DESCONTOS_PLANO NOCACHE;

-- Correção da Foreign Key para a tabela web_descontos
ALTER TABLE WEB_DESCONTOS_PLANO DROP CONSTRAINT FK_DESCONTOS_PLANO_DESC;

ALTER TABLE WEB_DESCONTOS_PLANO 
  ADD CONSTRAINT FK_DESCONTOS_PLANO_DESC FOREIGN KEY (DES_CODDESCONTO) REFERENCES WEB_DESCONTOS (CODDESCONTO);
