--
-- Armazena os produtos visitados pelo cliente até a finalização da compra.
-- 5000 registros p/dia.
--
  CREATE TABLE "WEBSITE"."WEB_PRODUTOS_VISITADOS" 
   (	"ID" NUMBER(15) NOT NULL, 
	"CODPROD_COMPRADO" NUMBER(6) NOT NULL, 
	"CODPROD_VISITADO" NUMBER(6) NOT NULL, 
	"VISITAS" NUMBER(10) NOT NULL, 
	 CONSTRAINT "PK_VISITADOS" PRIMARY KEY ("ID")
  CONSTRAINT "UK_VISITADOS_CODPROD" UNIQUE ("CODPROD_COMPRADO", "CODPROD_VISITADO"));
