--
-- Armazena os selos de produtos do site
-- 30 registros total
--

  CREATE TABLE "WEBSITE"."WEB_SELO" 
   (	"CODIGO" NUMBER(6,0) NOT NULL ENABLE, 
	"DTINICIO" DATE NOT NULL ENABLE, 
	"DTFINAL" DATE NOT NULL ENABLE, 
	"FORNECEDOR" NUMBER(6,0), 
	"LINHA" NUMBER(3,0), 
	"FAMILIA" NUMBER(3,0), 
	"GRUPO" NUMBER(3,0), 
	"DESCRICAO" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"TPSELO" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE, 
	"DTALTER" DATE, 
	"USALTER" VARCHAR2(20 BYTE), 
	"BANNER" NUMBER(6,0), 
	 CONSTRAINT "WEB_SELO_PK" PRIMARY KEY ("CODIGO")
  USING INDEX, 
	 CONSTRAINT "WEB_SELO_WEB_EMPRESA_FK1" FOREIGN KEY ("FORNECEDOR")
	  REFERENCES "WEBSITE"."WEB_EMPRESA" ("CODEMPRESA") ENABLE, 
	 CONSTRAINT "WEB_SELO_WEB_LINHA_FK1" FOREIGN KEY ("LINHA")
	  REFERENCES "WEBSITE"."WEB_LINHA" ("CODLINHA") ENABLE, 
	 CONSTRAINT "WEB_SELO_WEB_FAMILIA_FK1" FOREIGN KEY ("FAMILIA")
	  REFERENCES "WEBSITE"."WEB_FAMILIA" ("CODFAM") ENABLE, 
	 CONSTRAINT "WEB_SELO_WEB_GRUPO_FK1" FOREIGN KEY ("GRUPO")
	  REFERENCES "WEBSITE"."WEB_GRUPO" ("CODGRUPO") ENABLE, 
	 CONSTRAINT "WEB_SELO_WEB_TPSELO_FK1" FOREIGN KEY ("TPSELO")
	  REFERENCES "WEBSITE"."WEB_TPSELO" ("CODIGO") ENABLE, 
	 CONSTRAINT "WEB_SELO_WEB_BANNER_FK1" FOREIGN KEY ("BANNER")
	  REFERENCES "WEBSITE"."WEB_BANNER" ("CODBANNER") ENABLE
   );

--### projeto 1977 - site premium ###
alter table web_selo add theme varchar2(50) default 'site';
-- Aquiles B. da Silva 12/01/2012
alter table web_selo modify linha number(6,0);
alter table web_selo modify grupo number (6,0);
alter table web_selo modify familia number (6,0);
-- Aquiles CWI 14/10/13 - selos sobrepostos
alter table web_selo add posicao_selo number(2,0);   