CREATE TABLE "WEBSITE"."WEB_ESTILO"
(	"LINK_IMAGEM_LOGOTIPO" VARCHAR2(200 BYTE),
"COR_MENU_SUPERIOR" VARCHAR2(6 BYTE),
"LINK_IMAGEM_FUNDO_TOPO" VARCHAR2(200 BYTE),
"COR_FONTE" VARCHAR2(6 BYTE),
"COR_LABEL" VARCHAR2(6 BYTE),
"LINK_IMAGEM_CESTA" VARCHAR2(200 BYTE),
"COR_FONTE_MENU_SUPERIOR" VARCHAR2(6 BYTE),
"ID_ESTILO" NUMBER(6,0) NOT NULL ENABLE,
"DESCRICAO" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"LINK_BOTAO_BUSCA" VARCHAR2(200 BYTE),
"EXIBIR_SOMBRA" CHAR(1 BYTE),
 CONSTRAINT "WEB_ESTILO_PK" PRIMARY KEY ("ID_ESTILO")
);

Insert into WEB_ESTILO (LINK_IMAGEM_LOGOTIPO,COR_MENU_SUPERIOR,LINK_IMAGEM_FUNDO_TOPO,COR_FONTE,COR_LABEL,LINK_IMAGEM_CESTA,COR_FONTE_MENU_SUPERIOR,ID_ESTILO,DESCRICAO,LINK_BOTAO_BUSCA,EXIBIR_SOMBRA) values ('http://www.colombo.com.br/site/layouts/v1/img/LogoColomboVocePodeVoceMerece.png','142752','http://www.colombo.com.br/site/layouts/v1/img/bg-topo.png','FFFFFF','D4B51D','http://www.colombo.com.br/site/layouts/v1/img/carrinho-compras.png','FFFFFF',1,'Padrão','http://www.colombo.com.br/site/layouts/v1/img/botao-busca.png','S');