--
-- Armazena os emails enviados na newsletter
-- 150.000 registros por envio, 3x por semana
--

  CREATE TABLE "WEBSITE"."WEB_MAIL_USUARIOS" 
   (	"COD_MAIL" NUMBER NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"STATUS" CHAR(1 BYTE) DEFAULT '', 
	"DTENVIO" DATE, 
	"DTLEITURA" DATE, 
	 CONSTRAINT "WEB_MAIL_USUARIOS_PK" PRIMARY KEY ("COD_MAIL", "EMAIL")
  USING INDEX, 
	 CONSTRAINT "WEB_MAIL_USUARIOS_WEB_MAI_FK1" FOREIGN KEY ("COD_MAIL")
	  REFERENCES "WEBSITE"."WEB_MAIL_MARKETING" ("CODIGO") ENABLE, 
	 CONSTRAINT "WEB_MAIL_USUARIOS_WEB_USU_FK1" FOREIGN KEY ("EMAIL")
	  REFERENCES "WEBSITE"."WEB_USUARIOS_EMAIL" ("EMAIL") ENABLE
   );
 
 -- 21/08/2007 - Peterson - Alterada a Chave estrangeira devido ao e-mail incluídos pelo sistema
 ALTER TABLE WEB_MAIL_USUARIOS DROP CONSTRAINT WEB_MAIL_USUARIOS_WEB_USU_FK1