  CREATE TABLE "WEBSITE"."WEB_PROMO_NOTEBOOK" 
   (	"CODIGO" NUMBER(10,0) NOT NULL ENABLE, 
	"NOME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ENDERECO" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"CEP" NUMBER(8,0) NOT NULL ENABLE, 
	"DDD" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"FONE" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"RESPOSTA" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"PROFISSAO" VARCHAR2(100 BYTE), 
	 CONSTRAINT "WEB_PROMO_NOTEBOOK_PK" PRIMARY KEY ("CODIGO"))