CREATE TABLE "WEBSITE"."WEB_LAYOUT"
(	"COD_LINHA" NUMBER(3,0),
"DATA_INICIO" DATE,
"DATA_FIM" DATE,
"FLATIVO" CHAR(1 BYTE),
"ID_LAYOUT" NUMBER(6,0) NOT NULL ENABLE,
"ID_ESTILO" NUMBER(6,0) NOT NULL ENABLE,
"TIPO" NUMBER(1,0) NOT NULL ENABLE,
 CONSTRAINT "WEB_LAYOUT_PK" PRIMARY KEY ("ID_LAYOUT"),
 CONSTRAINT "FK_WEB_LAYOUT_ESTILO" FOREIGN KEY ("ID_ESTILO")
  REFERENCES "WEBSITE"."WEB_ESTILO" ("ID_ESTILO") ENABLE,
 CONSTRAINT "FK_WEB_LAYOUT_LINHA" FOREIGN KEY ("COD_LINHA")
  REFERENCES "WEBSITE"."WEB_LINHA" ("CODLINHA") ON DELETE CASCADE ENABLE
);

Insert into WEB_LAYOUT (COD_LINHA,DATA_INICIO,DATA_FIM,FLATIVO,ID_LAYOUT,ID_ESTILO,TIPO) values (null,null,null,'S',1,1,2);