CREATE TABLE "WEBSITE"."WEB_CARROSSEL_CONJUNTO" (
	"IDCARROSSELCONJUNTO" NUMBER(6,0) NOT NULL ENABLE,
	"TITULO" VARCHAR2(50 BYTE),
	"DATA_INICIAL" DATE NOT NULL ENABLE,
	"DATA_FINAL" DATE NOT NULL ENABLE,
	"FILIAL" NUMBER(6,0) NOT NULL ENABLE,
	CONSTRAINT "CARROSSEL_CONJUNTO_PK" PRIMARY KEY ("IDCARROSSELCONJUNTO")
);