--------------------------------------------------------
--  DDL for Table WEB_SOCIAL_USERCONNECTION
--------------------------------------------------------

  CREATE TABLE "WEBSITE"."WEB_SOCIAL_USERCONNECTION" 
   (    "USERID" VARCHAR2(255 BYTE), 
    "PROVIDERID" VARCHAR2(255 BYTE), 
    "PROVIDERUSERID" VARCHAR2(255 BYTE), 
    "RANK" NUMBER(38,0), 
    "DISPLAYNAME" VARCHAR2(255 BYTE), 
    "PROFILEURL" VARCHAR2(512 BYTE), 
    "IMAGEURL" VARCHAR2(512 BYTE), 
    "ACCESSTOKEN" VARCHAR2(255 BYTE), 
    "SECRET" VARCHAR2(255 BYTE), 
    "REFRESHTOKEN" VARCHAR2(255 BYTE), 
    "EXPIRETIME" NUMBER(20,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 505
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SITE_DAT" ;
--------------------------------------------------------
--  DDL for Index SYS_C00681316
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBSITE"."SYS_C00681316" ON "WEBSITE"."WEB_SOCIAL_USERCONNECTION" ("USERID", "PROVIDERID", "PROVIDERUSERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 505
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SITE_DAT" ;
--------------------------------------------------------
--  DDL for Index USERCONNECTIONRANK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBSITE"."USERCONNECTIONRANK" ON "WEBSITE"."WEB_SOCIAL_USERCONNECTION" ("USERID", "PROVIDERID", "RANK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 505
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SITE_DAT" ;
--------------------------------------------------------
--  Constraints for Table WEB_SOCIAL_USERCONNECTION
--------------------------------------------------------

  ALTER TABLE "WEBSITE"."WEB_SOCIAL_USERCONNECTION" MODIFY ("USERID" NOT NULL ENABLE);
 
  ALTER TABLE "WEBSITE"."WEB_SOCIAL_USERCONNECTION" MODIFY ("PROVIDERID" NOT NULL ENABLE);
 
  ALTER TABLE "WEBSITE"."WEB_SOCIAL_USERCONNECTION" MODIFY ("RANK" NOT NULL ENABLE);
 
  ALTER TABLE "WEBSITE"."WEB_SOCIAL_USERCONNECTION" MODIFY ("ACCESSTOKEN" NOT NULL ENABLE);
 
  ALTER TABLE "WEBSITE"."WEB_SOCIAL_USERCONNECTION" ADD PRIMARY KEY ("USERID", "PROVIDERID", "PROVIDERUSERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 505
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SITE_DAT"  ENABLE;