/*
CREATE TABLE "WEBSITE"."WEB_PROMO_MAES_INDIQUE" 
(	"NOME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
    "EMAIL" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
    "AMIGO1" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
    "EMAIL1" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
    "AMIGO2" VARCHAR2(100 BYTE), 
    "EMAIL2" VARCHAR2(100 BYTE), 
    "AMIGO3" VARCHAR2(100 BYTE), 
    "EMAIL3" VARCHAR2(100 BYTE) 
);
*/

alter table web_promo_maes_indique add constraint pk_web_promo_maes_indique primary key (nome);