
  CREATE TABLE WEB_CAMPANHA_PRECO_PORTAL
   (	CODIGO NUMBER(10,0),
	CPR_ID NUMBER(10,0),
	PORTAL NUMBER(10,0),
	 CONSTRAINT PK_CAMPANHA_PRECO_PORTAL PRIMARY KEY (CODIGO),
	 CONSTRAINT FK_CPR_ID FOREIGN KEY (CPR_ID) REFERENCES WEB_CAMPANHAS_PRECO (CPR_ID),
	 CONSTRAINT FK_PORTAL FOREIGN KEY (PORTAL) REFERENCES WEB_PORTAL (CODIGO),
	 constraint UK_WEB_CAMPANHA_PRECO_PORTAL unique (cpr_id,portal)
   );

