CREATE TABLE WEB_PROD_PERGUNTAS 
   (	ID NUMBER(10,0) NOT NULL ENABLE, 
   	PERGUNTA_ID NUMBER(10,0), 
	USUARIO_ID NUMBER(10,0), 
	PRODUTO_ID NUMBER(10,0) NOT NULL ENABLE, 
	TEXTO VARCHAR2(4000), 
	TEXTO_SITE VARCHAR2(4000), 
	RESPOSTA_SITE VARCHAR2(4000),
	DATA_CADASTRO DATE, 
	AVALIADOR VARCHAR2(255), 
	DATA_AVALIACAO DATE, 
	FL_APROVADA CHAR(1) DEFAULT 'N', 
	FL_APAGADA CHAR(1) DEFAULT 'N', 
	CONSTRAINT ID PRIMARY KEY (ID), 
	CONSTRAINT WEB_PROD_PERGUNTAS_FK FOREIGN KEY (PERGUNTA_ID) REFERENCES WEB_PROD_PERGUNTAS (ID), 
	CONSTRAINT PERGUNTAS_USUARIOS_FK FOREIGN KEY (USUARIO_ID) REFERENCES WEB_USUARIOS (CODCLILV),
	CONSTRAINT PERGUNTAS_PROD_FK FOREIGN KEY (PRODUTO_ID) REFERENCES WEB_PROD (CODPROD)
   );