--
-- Armazena os selos marcados para o produto
-- 1000 registros
--

  CREATE TABLE "WEBSITE"."WEB_PROD_SELO" 
   (	"PRODUTO" NUMBER(6,0) NOT NULL ENABLE, 
	"SELO" NUMBER(6,0) NOT NULL ENABLE, 
	"TIPO" VARCHAR2(1 BYTE) DEFAULT 'I' NOT NULL ENABLE, 
	 CONSTRAINT "WEB_PROD_SELO_PK" PRIMARY KEY ("PRODUTO", "SELO")
  USING INDEX, 
	 CONSTRAINT "WEB_PROD_SELO_WEB_PROD_FK1" FOREIGN KEY ("PRODUTO")
	  REFERENCES "WEBSITE"."WEB_PROD" ("CODPROD") ENABLE, 
	 CONSTRAINT "WEB_PROD_SELO_WEB_SELO_FK1" FOREIGN KEY ("SELO")
	  REFERENCES "WEBSITE"."WEB_SELO" ("CODIGO") ENABLE
   );
 
-- 27/09/2007 - Lucas - Campo de ordenacao
ALTER TABLE WEB_PROD_SELO ADD ("ORDEM" NUMBER(3));
