CREATE TABLE "WEBSITE"."WEB_ITPROD_BRINDE_GRUPOS"
  (
    "CODGRUPO"                 NUMBER(6,0) NOT NULL ENABLE,
    "VALOR"                    NUMBER(10,2),
    "VALOR_BOLETO"             NUMBER(10,2),
    "COD_BRINDE"               NUMBER(10,0) NOT NULL ENABLE,
    "CODPROD_REPRESENTATIVO"   NUMBER(6,0) NOT NULL ENABLE,
    "DESCRICAO_REPRESENTATIVA" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    CONSTRAINT "WEB_ITPROD_BRINDE_GRUPOS_PK" PRIMARY KEY ("CODGRUPO", "COD_BRINDE")
  )