CREATE TABLE "WEBSITE"."WEB_PEDIDOS_DESCONTOS"
  (
    "CODIGO"          NUMBER(10,0) NOT NULL ENABLE,
    "CODFIL"          NUMBER(3,0) NOT NULL ENABLE,
    "PEDIDO"          NUMBER(8,0) NOT NULL ENABLE,
    "MOTIVO_DESCONTO" NUMBER(10,0),
    "OBS"             VARCHAR2(80 BYTE),
    CONSTRAINT "PK_WEB_PEDIDOS_DESCONTO" PRIMARY KEY ("CODIGO"),
    CONSTRAINT "FK_PEDIDOS_DESC_MOTIVO" FOREIGN KEY ("MOTIVO_DESCONTO") REFERENCES "WEBSITE"."WEB_MOTIVOS_DESCONTOS" ("CODIGO")
  );