-- 9 registros por dia

  CREATE TABLE "WEBSITE"."WEB_CAMP_PRECO_PLANOS" 
   (	CPL_ID NUMBER(10) NOT NULL, 
	CPR_ID NUMBER(10) NOT NULL, 
	PLA_CODPLANO VARCHAR2(3), 
	CPL_JUROS NUMBER(5,2), 
        CPL_PARCELAS NUMBER(3) NOT NULL, 
        CPL_VALOR_VARIACAO NUMBER(15,2), 
	CPL_PERCENTUAL_VARIACAO NUMBER(5,2),
	CONSTRAINT "WEB_CAMP_PRECO_PLANOS_PK" PRIMARY KEY ("CPL_ID"),
        CONSTRAINT "WEB_CPL_FK_WEB_CPR" FOREIGN KEY (CPR_ID) REFERENCES "WEBSITE"."WEB_CAMPANHAS_PRECO" (CPR_ID),
        CONSTRAINT "WEB_CPL_FK_WEB_PLANO" FOREIGN KEY (PLA_CODPLANO) REFERENCES "WEBSITE"."WEB_PLANO" (CODPLANO)
);

CREATE SEQUENCE SEQ_ID_WEB_CAMP_PRECO_PLANOS INCREMENT BY 1 START WITH 1 ; 

-- 09/05/2012 - Aquiles - adicionar juros apartir de uma parcela especifica
ALTER TABLE WEB_CAMP_PRECO_PLANOS ADD ("CPL_JUROS_PARCELA" NUMBER(2) DEFAULT 1 NOT NULL);