--
-- Armazena os dados dos descontos dados pelo sistema do televendas
-- 2000 registros / mes
--
  CREATE TABLE "WEBSITE"."WEB_PROD_ACORDO_OK" 
   (	"CODIGO" NUMBER(6,0) NOT NULL ENABLE, 
	"PRODUTO" NUMBER(6,0) NOT NULL ENABLE, 
	"VENDEDOR" NUMBER(6,0) NOT NULL ENABLE, 
	"VALORPADRAO" NUMBER NOT NULL ENABLE, 
	"VALORACORDO" NUMBER NOT NULL ENABLE, 
	"DTACORDO" DATE NOT NULL ENABLE, 
	"USERADMIN" NUMBER(6,0), 
	 CONSTRAINT "WEB_PROD_ACORDO_OK_PK" PRIMARY KEY ("CODIGO") ENABLE
   ) ;
 