CREATE TABLE "WEBSITE"."WEB_MOTIVOS_DESCONTOS"
  (
    "CODIGO"    NUMBER(10,0),
    "DESCRICAO" VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "FL_ATIVO"  CHAR(1 BYTE),
    "FL_OBS"    CHAR(1 BYTE),
    CONSTRAINT "CK_MOTIVOS_DESCONTOS" CHECK (fl_ativo IN ('S','N')) ENABLE,
    CONSTRAINT "PK_MOTIVOS_DESCONTOS" PRIMARY KEY ("CODIGO")
  );