-- armazena planos por perfis
-- 100 registros
CREATE TABLE WEB_PLANO_PERFIL
   (CODPLANO VARCHAR2(3 BYTE) NOT NULL, 
    CODPERFIL NUMBER(3) NOT NULL,    
    FLREBATEFINANCEIRO CHAR(1 BYTE), 
    CONSTRAINT WEB_PLANO_PERFIL_PK PRIMARY KEY (CODPLANO,CODPERFIL),        
    CONSTRAINT WEB_PLANO_PERFIL_FK_TPPGTO FOREIGN KEY (CODPLANO)
	  REFERENCES WEB_PLANO (CODPLANO),
    CONSTRAINT WEB_PLANO_PERFIL_FK_PERFIL FOREIGN KEY (CODPERFIL)
      REFERENCES WEB_PERFIL (CODIGO)
    );