CREATE TABLE "WEBSITE"."WEB_REDIRECT"
  (
    "URL_ORIGEM"  VARCHAR2(350 BYTE) NOT NULL ENABLE,
    "URL_DESTINO" VARCHAR2(350 BYTE) NOT NULL ENABLE,
    "FL_ATIVO"    VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "DT_ALTERACAO" DATE NOT NULL ENABLE,
    "TP_REDIRECIONAMENTO" NUMBER(3,0) NOT NULL ENABLE,
    CONSTRAINT "WEB_REDIRECT_PK" PRIMARY KEY ("URL_ORIGEM")  ENABLE
  )
  