CREATE TABLE "WEBSITE"."WEB_COMPARADOR_EMPRESA"
  (
    "CODEMPRESA" NUMBER(10,0) NOT NULL ENABLE,
    "DESCRICAO"  VARCHAR2(60 BYTE) NOT NULL ENABLE,
    "FLATIVO"    NUMBER(1,0),
    CONSTRAINT "WEB_EMPRESA_COMPARADOR_PK" PRIMARY KEY ("CODEMPRESA")  ENABLE
  )
  