  CREATE TABLE "WEBSITE"."WEB_INDIQUE_AMIGO" 
   (	"CODIGO" NUMBER(10,0) NOT NULL ENABLE, 
	"NOME" VARCHAR2(100 BYTE), 
	"NOME_AMIGO" VARCHAR2(80 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"EMAIL_AMIGO" VARCHAR2(100 BYTE), 
	"DT_CADASTRO" DATE, 
	"MENSAGEM" VARCHAR2(300 BYTE), 
	"FL_ENVIADO_RESPONSYS" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"CODPROD" NUMBER(10,0), 
	"URL_ENVIAR" VARCHAR2(200 BYTE), 
	 CONSTRAINT "WEB_INDIQUE_AMIGO_PK" PRIMARY KEY ("CODIGO") ENABLE, 
	 CONSTRAINT "WEB_INDIQUE_AMIGO_WEB_PRO_FK1" FOREIGN KEY ("CODPROD")REFERENCES "WEBSITE"."WEB_PROD" ("CODPROD") ENABLE
   ) ;
 
