/*
  CREATE TABLE "WEBSITE"."WEB_ITPROD_BRINDE_HIS" 
   ("COD_BRINDE" NUMBER(10,0), 
	"COD_ITPROD_PRINCIPAL" NUMBER(10,0), 
	"VALOR" NUMBER(10,2), 
	"VALOR_BOLETO" NUMBER(10,2), 
	"DT_ALTERACAO" DATE, 
	"USR_ALTERACAO" VARCHAR2(60 BYTE), 
	"OPERACAO_ALTERACAO" VARCHAR2(60 BYTE), 
	"FL_ATIVO" CHAR(1 BYTE)
   );
*/

alter table WEB_ITPROD_BRINDE_HIS add constraint pk_WEB_ITPROD_BRINDE_HIS primary key (cod_brinde, dt_alteracao);